### ISSUE TITLE
How to tranfer avax in C chain after the network up

### ISSUE THREAD

**Issue by huahuayu** [ava-labs/avalanche-network-runner#119]
Hi, may I know how to tranfer avax in C chain after the network up. I have success started a local network, but I don't know how to transfer funds to C chain address (which address I have the etheruem format private key), please take a look of this issue https://github.com/ava-labs/avalanchego/issues/1041 for reference.

**Comment by ceyonur** [comment]
See this document: https://docs.avax.network/build/tutorials/platform/fund-a-local-test-network

**Comment by huahuayu** [comment]
thanks @ceyonur
