### ISSUE TITLE
Can't run successfully avalanche-network-tunner

### ISSUE THREAD

**Issue by DDiscua504** [ava-labs/avalanche-network-runner#143]
Hi, 

I been trying to run the following command : 

avalanche-network-runner control start --log-level debug --endpoint="=127.0.0.1:8080" --number-of-nodes=5 --avalanchego-path "/home/ubuntu/go/src/github.com/ava-labs/avalanchego/build/avalanchego" --global-node-config '{"index-enabled":false, "api-admin-enabled":true,"network-peer-list-gossip-frequency":"300ms", "public-ip":"PUBLIC IP"}'. But I always got this error message.

![Screen Shot 2022-05-09 at 20 10 46](https://user-images.githubusercontent.com/79107336/167528359-65a4fd69-bb7f-475d-ba40-9091cb04719d.png)

**Comment by DDiscua** [comment]
When I run http calls, crash and ends like : 

curl -X POST -k http://localhost:8081/v1/control/start -d '{"execPath":"'${AVALANCHEGO_EXEC_PATH}'","numNodes":2,"logLevel":"INFO","pluginDir":"'${AVALANCHEGO_PLUGIN_PATH}'"}'

![image](https://user-images.githubusercontent.com/31171755/167905809-1580ffd5-4d64-4e2b-8628-90617af7de89.png)

**Comment by vishnuram1999** [comment]
> Hi,
> 
> I been trying to run the following command :
> 
> avalanche-network-runner control start --log-level debug --endpoint="=127.0.0.1:8080" --number-of-nodes=5 --avalanchego-path "/home/ubuntu/go/src/github.com/ava-labs/avalanchego/build/avalanchego" --global-node-config '{"index-enabled":false, "api-admin-enabled":true,"network-peer-list-gossip-frequency":"300ms", "public-ip":"PUBLIC IP"}'. But I always got this error message.
> 
> ![Screen Shot 2022-05-09 at 20 10 46](https://user-images.githubusercontent.com/79107336/167528359-65a4fd69-bb7f-475d-ba40-9091cb04719d.png)

When running with the binary avalanche-network-runner, it runs a server process as an RPC server which then waits for API calls and handles them. **Therefore we run one shell with the RPC server, and another one for issuing calls.**

To start the RPC server 
```
avalanche-network-runner server \
--log-level debug \
--port=":8080" \
--grpc-gateway-port=":8081"
```

Then start your five node system in another terminal/shell using your command.
