### ISSUE TITLE
Remote deployments

### ISSUE THREAD

**Issue by kirillt** [ava-labs/avalanche-network-runner#145]
Would be great to make the runner capable of remote deployments. This would require messing with SSH and/or Kubernetes. In my opinion, simple SSH implementation would be fine.

Please, fix me if this doesn't sound right:
1. Generate Genesis from simple configuration (required `IP:PORT` pairs and regular `avalanche-network-runner` parameters).
2. Endpoints might be required to have `avalanchego` pre-installed or we can copy it using SCP.
3. SCP Genesis file, run `avalanchego` over SSH, should be similar to regular flow.

**Comment by dasconnor** [comment]
This is a good idea, but I don't think we're going to add this to the ANR's roadmap at this time.
