### ISSUE TITLE
can not start local testnet for v1.1.0

### ISSUE THREAD

**Issue by chris-lee-lb** [ava-labs/avalanche-network-runner#166]
Currently I can not successfully start local testnet with avalanche-network-runner, but successfully with manually start. (which all follow by this quick start guideline <https://docs.avax.network/quickstart/create-a-local-test-network/> )

Here is reproducible scripts

```dockerfile
FROM ubuntu:22.04

RUN export PATH="${PATH}:/usr/lib/go-1.17/bin:/root/go/bin" && \
    apt-get update && \
    apt-get install -y --no-install-recommends curl ca-certificates net-tools git golang-1.17 gcc libc6-dev && \
    cd /tmp && \
    git clone https://github.com/ava-labs/avalanche-network-runner.git && cd ./avalanche-network-runner && \
    ./scripts/tests.e2e.sh 1.7.8 1.7.9
```

And there is the [output.log](https://github.com/ava-labs/avalanche-network-runner/files/8875164/output.log)

**Comment by TtheBC01** [comment]
I'm having problems getting this tools to work in a docker environment as well. If I run directly on native host, like a Ubuntu 18.04 VM, the avalanche-network-runner tool works great, but when I try to containerize my setup like you are doing, the tool fails as it shows in your output logs.

**Comment by johnthethird** [comment]
It looks like `avalanche-network-runner` uses ipv6 for p2p comms, so try enabling ipv6 on your docker host, add this to your engine config:

```json
{
  "fixed-cidr-v6": "2001:db8:1::/64",
  "ipv6": true
}
```

**Comment by TtheBC01** [comment]
works, thanks!

**Comment by felipemadero** [comment]
@chris-lee-lb was your problem solved by @johnthethird suggestion?
