### ISSUE TITLE
Error: unknown flag: --network-id

### ISSUE THREAD

**Issue by imjxlian** [ava-labs/avalanche-network-runner#252]
Hello,

I'm trying to run 5 nodes but when they start there is an error : `Error: unknown flag: --network-id`

In one terminal I run my server with :
```
avalanche-network-runner server \
--log-level debug \
--port=":8080" \
--grpc-gateway-port=":8081"
```

Then I run this command in another one : 
`curl -X POST -k http://localhost:8081/v1/control/start -d '{"execPath":"'${AVALANCHEGO_EXEC_PATH}'","numNodes":5,"logLevel":"INFO"}'`

Is it a bug ?

<img width="1213" alt="Capture d’écran 2022-08-29 à 15 14 03" src="https://user-images.githubusercontent.com/22702056/187219601-be81ecb3-6e15-4d2d-bd6f-2c4fd809a496.png">

**Comment by felipemadero** [comment]
Hi. It does not seem to be a bug. It seems you are passing the path to `avalanche-network-runner` binary in `AVALANCHEGO_EXEC_PATH` variable, but you should pass the path to the avalanchego binary (e.g., ${HOME}/go/src/github.com/ava-labs/avalanchego/build/avalanchego, that depends on where you installed avalanchego). Please confirm the value of `AVALANCHEGO_EXEC_PATH`
