### ISSUE TITLE
Update default genesis to support Banff

### ISSUE THREAD

**Issue by rana-azureus** [ava-labs/avalanche-network-runner#308]
I believe the genesis is now missing `apricotPhase6BlockTimestamp` and `banffBlockTimestamp` values. Upgrading to avalanchego v1.9.0 resulted in a local network which didn't work without these values.

**Comment by felipemadero** [comment]
could you specify the operation that is not working?

**Comment by felipemadero** [comment]
also, could you check your problem against update-genesis-to-banff branch ?

**Comment by rana-azureus** [comment]
> could you specify the operation that is not working?

Yes sorry. Making a transaction on the network seemed to hang indefinitely even though the network started.

**Comment by felipemadero** [comment]
> > could you specify the operation that is not working?
> 
> Yes sorry. Making a transaction on the network seemed to hang indefinitely even though the network started.

Sorry for the delay. Could you pass me the specific tx example?

**Comment by felipemadero** [comment]
Genesis was updated on Nov 2022
