### ISSUE TITLE
 Please remove the dirty remap on cloning dependencies

### ISSUE THREAD

**Issue by PaTiToMaSteR** [ava-labs/avalanche-network-runner#382]
![image](https://user-images.githubusercontent.com/3490937/208993646-b70f5e39-1e94-4d3a-8af7-c254016fa405.png)

Is there any reason for this? I'm stuck with the build script in linux because of that :S

**Comment by danlaine** [comment]
This is resolved by https://github.com/ava-labs/avalanche-network-runner/pull/380 which should be merged into `main` fairly soon

**Comment by danlaine** [comment]
Closing this as #380 has been merged into main
