### ISSUE TITLE
Print debug information on errors

### ISSUE THREAD

**Issue by holisticode** [ava-labs/avalanche-network-runner#411]
When we have errors, we have to look up the correct log directory manually and search for errors.

Provide a way (for clients especially) to be able to get to logs in an error case.

Suggestions:

* Both LoadSnapshot and CreateBlockchains could return a BackendRunDir param in the response
* This way the cli doesn't actually have to poke around looking for the correct run directory by timestamp or something, but actually has some "reference"

Another way could be to add a new ANR endpoint GetLogs and/or GetErrorLogs which would be called before the backend is shut down when the cli hits an error from the backend. Downside of this is that if the server crashed, we don't get anything

**Comment by felipemadero** [comment]
> When we have errors, we have to look up the correct log directory manually and search for errors.
> 
> Provide a way (for clients especially) to be able to get to logs in an error case.
> 
> Suggestions:
> 
> * Both LoadSnapshot and CreateBlockchains could return a BackendRunDir param in the response
> * This way the cli doesn't actually have to poke around looking for the correct run directory by timestamp or something, but actually has some "reference"
> 
> Another way could be to add a new ANR endpoint GetLogs and/or GetErrorLogs which would be called before the backend is shut down when the cli hits an error from the backend. Downside of this is that if the server crashed, we don't get anything

I think best way is for the CLI to have state on the current log dir, based on currently available info from ANR server cluster info + node info. Not adding functionality to ANR for the moment.

**Comment by dasconnor** [comment]
Solved in CLI
