### ISSUE TITLE
Fix `--genesis` flag warning

### ISSUE THREAD

**Issue by cgcardona** [ava-labs/avalanche-network-runner#618]
To reproduce I follow these steps

1. Start the ANR server. `avalanche-network-runner server
2. Start a 5 node network via "Start". You should see it in the logs very soon. Attached is a screenshot.

```zsh
[node1] Flag --genesis has been deprecated, use --genesis-file instead
```

<img width="1783" alt="Screenshot 2023-07-21 at 12 49 29 PM" src="https://github.com/ava-labs/avalanche-network-runner/assets/260614/33076ed9-f4b3-474d-b50a-e1350b2a61ae">

**Comment by felipemadero** [comment]
notice: avago version for this problem was 1.10.2
